### PR TITLE
Code improvements for internal pipeline

### PR DESCRIPTION
**Pull request by ambiknai**

### CODE REVIEW

**Review by Bhagyashreek8 — APPROVED** [review]
lgtm

**Review by ashimagarg27 — CHANGES_REQUESTED** [review]
Changes looks Good, One query: Is golangci linter running for this repo as I don't see golangci yaml file here

**Comment by ambiknai** [comment]
> Changes looks Good, One query: Is golangci linter running for this repo as I don't see golangci yaml file here

Hi Ashima
We have bt lint configured for internal(alchemy-containers) repo. So once this code is pulled and linter is run over the code, it will fail/pass travis .

**Review by ashimagarg27 — APPROVED** [review]

**Review by nkkashyap — APPROVED** [review]
lgtm

**Pull request merged**
